# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9de2c63a5d0b1a261ba028f56414ce1a3d27fc966773283dc3bbe2abed39ed86fbf47d9c7b32a42f2323e32725714c5a88b04bf4418ae5c5a872df46aba5567c

test:
  secret_key_base: ab49acdaa883d0d0973309e5e967bcbaac4e71cad71f02d24124985eab1138a331a695d1b842eab5d29312056605055c0da147402d1f4c79f2855590c079d205

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
